DROP TABLE IF EXISTS url_checks;
DROP TABLE IF EXISTS urls_689c;

CREATE TABLE urls_689c(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL UNIQUE
);

CREATE TABLE url_checks(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    url_id BIGINT REFERENCES urls_689c(id),
    status_code INTEGER NOT NULL,
    h1 TEXT,
    title TEXT,
    description TEXT,
    created_at TIMESTAMP NOT NULL UNIQUE
);