<?php include_once('_header.phtml') ?>
<main class="container-lg mt-3">
    <h1>Сайты</h1>
    <table class="table table-bordered" data-test="urls">
        <thead>
            <tr>
                <th>ID</th>
                <th>Имя</th>
                <th>Последняя проверка</th>
                <th>Код ответа</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($urls as $url): ?>
                <tr>
                    <td><?= $url->getId() ?></td>
                    <td><a href="urls/<?= $url->getId() ?>"><?= $url->getName() ?></a></td>
                    <?php $checks = $url->getChecks() ?>
                    <td><?= $checks['created_at'] ?></td>
                    <td><?= $checks['status_code'] ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</main>
<?php include_once('_footer.phtml') ?>