include_once('/_header.phtml');
<h1>Сайт: <?= $url->getName() ?></h1>
<table class="table" data-test="url">
    <tbody>
        <tr>
            <td>ID</th>
            <td><?= $url->getId() ?></th>
        </tr>
        <tr>
            <td>Имя</th>
            <td><?= $url->getName() ?></th>
        </tr>
        <tr>
            <td>Дата создания</th>
            <td><?= $url->getCreatedAt() ?></th>
        </tr>
    </tbody>
</table>
<h2 class="mt-5 mb-3">Проверки</h2>
<form action="/urls/<?= $url->getId() ?>/checks" method="post">
    <input type="submit" value="Запустить проверку" class="btn btn-primary">
</form>
<table class="table" data-test="checks">
    <thead>
        <tr>
            <th>ID</th>
            <th>Код ответа</th>
            <th>h1</th>
            <th>title</th>
            <th>description</th>
            <th>Дата создания</th>
        </tr>
    </thead>
</table>
include_once('/_footer.phtml');