<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hexlet project3</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body class="min-vh-100 d-flex flex-column">
    <header>
    <nav class="navbar navbar-expand-lg px-3 navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Анализатор страниц</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Главная</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="#">Сайты</a>
                </li>
            </ul>
        </div>
    </nav>
    </header>
    <main class="flex-grow-1 mt-3">
        <div class="container-lg mt-3">
            <div class="row">
                <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                    <h1 class="display-3">Анализатор страниц</h1>
                    <p>Бесплатно проверяйте сайты на SEO пригодность</p>
                    <form action="/urls" method="get" class="row">
                        <div class="col-8">
                            <label for="text" class="visually-hidden"></label>
                            <input type="text" name="url[name]" id="text" class="form-control form-control-lg" placeholder="https://www.example.com">
                        </div>
                        <div class="col-2">
                            <input class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3" type="submit" value="Проверить">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
    <footer class="border-top py-3 mt-5 flex-shrink-0">
        <div class="container-lg">
            <div class="row">
                <div class="col-12 text-center">
                    <a href="https://hexlet.io/about">Hexlet</a>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>