<?php include_once('urls/_header.phtml') ?>
   <main class="flex-grow-1 mt-3">
        <div class="container-lg mt-3">
            <div class="row">
                <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                    <h1 class="display-3">Анализатор страниц</h1>
                    <p>Бесплатно проверяйте сайты на SEO пригодность</p>
                    <form action="/urls" method="post" class="row">
                        <div class="col-8">
                            <label for="text" class="visually-hidden"></label>
                            <input type="text" name="url[name]" id="text" class="form-control form-control-lg <?= !empty($errors) ? 'is-invalid' : '' ?> " placeholder="https://www.example.com" value=<?=$data?>>
                            <?php foreach($errors as $error) :?>
                                <?php foreach($error as $message) :?>
                                    <div class="invalid-feedback"><?= $message?></div>
                                <?php endforeach ;?>        
                            <?php endforeach ;?>
                        </div>
                        <div class="col-2">
                            <input class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3" type="submit" value="Проверить">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
<?php include_once('urls/_footer.phtml') ?>